version: "3.3"
services:
  clickhouse1:
    image: clickhouse/clickhouse-server:22.9-alpine
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  haproxy:
    image: haproxy:2.6.7-alpine
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8080:8080
      - 8405:8405
